---
- hosts: mod_relays
  tasks:
  - hostname: name='{{inventory_hostname}}'

  - debconf:
      name: postfix
      question: postfix/main_mailer_type
      value: 'Internet Site'
      vtype: select
    when: ansible_distribution == 'Ubuntu'

  - debconf:
      name: postfix
      question: postfix/mailname
      value: '{{inventory_hostname}}'
      vtype: string
    when: ansible_distribution == 'Ubuntu'

  - package:
      name:
      - firewalld
      - fail2ban-firewalld
      state: absent
    when: ansible_distribution == 'Fedora'
      
  - package:
      name:
      - perl
      - postfix
      - procmail
      - sed
      - dos2unix
      - grep
      - coreutils
      - diffutils
      - logwatch
      - ufw

  - apt:
      name:
      - fail2ban
      # For Ansible
      - python
      - mailutils
      - apticron
      # For relay-bounce-monitor.pl
      - libtimedate-perl
    when: ansible_distribution == 'Ubuntu'

  - dnf:
      name:
      - fail2ban-server
      - fail2ban-sendmail
      # For Ansible
      - python2
      - mailx
      - yum-updatesd
      # For relay-bounce-monitor.pl
      - perl-TimeDate
    when: ansible_distribution == 'Fedora'

  - command: getenforce
    register: getenforce
    failed_when: false
    changed_when: false

  - block:
    # Required by Ansible when selinux is being enforced
    - apt: name=python-selinux
      when: ansible_distribution=='Ubuntu'
    - dnf:
        name:
        - python2-libselinux
        - python2-policycoreutils
      when: ansible_distribution == 'Fedora'
    when: 'getenforce.stdout is defined and "Enforcing" in getenforce.stdout'

  - block:
    - ini_file:
        dest: /etc/yum/yum-updatesd.conf
        section: main
        option: run_interval
        value: 86400  # daily
    - ini_file:
        dest: /etc/yum/yum-updatesd.conf
        section: main
        option: emit_via
        value: email
    when: ansible_distribution == 'Fedora'

  # https://github.com/ansible/ansible/issues/43670
  - shell: grep -q -s '^mtm:!:' /etc/shadow
    ignore_errors: true
    failed_when: false
    changed_when: false
    register: mtm_locked

  - user: name=mtm password_lock=yes
    when: mtm_locked.rc != 0

  - file: dest=/home/mtm/bin state=directory

  - copy: src=mtm.sh dest=/home/mtm/bin/mtm.sh mode=0755

  - copy:
      dest: /home/mtm/.procmailrc
      content: |
        :0 HB
        * X-BeenThere: mtm@{{inventory_hostname}}
        /dev/null

        :0 w
        |$HOME/bin/mtm.sh

        :0 w
        |mail -s 'mtm message' root

  # https://github.com/ansible/ansible/issues/43670
  - shell: grep -q -s '^modupdate:!:' /etc/shadow
    ignore_errors: true
    failed_when: false
    changed_when: false
    register: modupdate_locked

  - user: name=modupdate password_lock=yes
    when: modupdate_locked.rc != 0

  - name: install /home/modupdate/.procmailrc
    copy:
      dest: /home/modupdate/.procmailrc
      content: |
        LOGFILE=$HOME/procmail.log
        VERBOSE=on

        :0 w
        * From: .*moderators-update@lists\.eyrie\.org
        * Subject: Update to news moderated group aliases
        |$HOME/bin/modupdate.sh;

        :0
        * Subject: Diff of updated moderated newsgroup aliases
        /dev/null

        :0 w
        |mail -s 'modupdate message' root

  - file: dest=/home/modupdate/bin state=directory

  - copy:
      src: modupdate.sh
      dest: /home/modupdate/bin/modupdate.sh
      mode: 0755

  - file:
      dest: /home/modupdate/aliases
      owner: modupdate
      group: modupdate
      state: directory

  - copy:
      src: aliases
      dest: /home/modupdate/aliases/aliases
      owner: modupdate
      group: modupdate
      mode: 0644
      force: no
    register: aliases_changed

  - name: disable bouncing aliases
    lineinfile:
      dest: /home/modupdate/aliases/aliases
      regexp: '^{{item}}:'
      line: '{{item}}:	mod-bounce.no-mod-info@isc.org'
    # List aliases here that are bouncing and haven't been updated in
    # the master aliases list yet. When there aren't any pending
    # updates, set this to [].
    with_items: []
    register: aliases_fixes

  - command: /usr/sbin/postalias /home/modupdate/aliases/aliases
    when: aliases_changed.changed or aliases_fixes.changed

  - lineinfile:
      dest: /etc/aliases
      line: 'root: {{root_email_address}}'
      regexp: '^\s*root\s*:'
    when: root_email_address is defined
    register: root_alias

  - command: newaliases
    when: root_alias.changed

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^alias_maps\s*='
      line: 'alias_maps = hash:/etc/aliases hash:/home/modupdate/aliases/aliases'
    register: alias_maps

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^myhostname\s*='
      line: 'myhostname = {{inventory_hostname}}'
    register: myhostname

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^mydestination\s*='
      line: 'mydestination = $myhostname, localhost.$mydomain, localhost, moderators.isc.org, moderators.uu.net'
    register: mydestination

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^mailbox_command\s*='
      line: 'mailbox_command = /usr/bin/procmail -a "$EXTENSION"'
    register: mailbox_command

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^smtpd_recipient_restrictions\s*='
      line: 'smtpd_recipient_restrictions = permit_mynetworks, reject_rbl_client zen.spamhaus.org, permit_mx_backup, reject_unauth_destination'
    register: smtpd_recipient_restrictions

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^compatibility_level\s*='
      line: 'compatibility_level = 2'
    register: compatibility_level

  - lineinfile:
      dest: /etc/postfix/main.cf
      regexp: '^inet_interfaces\s*='
      line: 'inet_interfaces = all'
    register: inet_interfaces

  - service: name=postfix enabled=yes

  - service: name=postfix state=restarted
    when: myhostname.changed or mydestination.changed or
          mailbox_command.changed or smtpd_recipient_restrictions.changed or
          compatibility_level.changed or inet_interfaces.changed

  - copy:
      dest: /etc/cron.hourly/snitch
      mode: 0755
      content: |
        #!/bin/bash -e

        touch /root/filesystem-is-ok
        rm /root/filesystem-is-ok
        sleep 1 | telnet localhost 25 2>/dev/null | grep -q -s Postfix
        curl '{{snitch_url}}' &> /dev/null
    when: snitch_url is defined

  - copy:
      dest: /usr/local/bin/relay-bounce-monitor.pl
      src: relay-bounce-monitor.pl
      mode: 0755

  - file:
      dest: /etc/cron.daily/relay-bounce-monitor
      state: link
      src: /usr/local/bin/relay-bounce-monitor.pl

  - ini_file:
      dest: /etc/fail2ban/jail.local
      create: yes
      section: DEFAULT
      option: backend
      value: polling
    register: fail2ban_backend

  - ini_file:
      dest: /etc/fail2ban/jail.local
      create: yes
      section: postfix
      option: enabled
      value: true
    register: fail2ban_postfix_jail

  - service: name=fail2ban enabled=yes state=restarted
    when: fail2ban_backend.changed or fail2ban_postfix_jail.changed

  - service: name=fail2ban enabled=yes state=started
    when: not (fail2ban_backend.changed or fail2ban_postfix_jail.changed)

  - lineinfile:
      dest: /etc/logwatch/conf/services/secure.conf
      create: yes
      line: '*Remove = New seat seat[0-9]+\.$'

  - lineinfile:
      dest: /etc/logwatch/conf/services/secure.conf
      line: '*Remove = Watching system buttons on /dev/input'

  - lineinfile:
      dest: /etc/logwatch/conf/services/secure.conf
      line: '*Remove = Cannot create session: Already running in a session'

  - lineinfile:
      dest: /etc/logwatch/conf/services/secure.conf
      line: '*Remove = echo BECOME-SUCCESS-'

  - lineinfile:
      dest: /etc/logwatch/conf/services/rsyslogd.conf
      create: yes
      line: "*OnlyService = rsyslogd"
      insertbefore: '\*Remove'
      firstmatch: yes

  - lineinfile:
      dest: /etc/logwatch/conf/services/rsyslogd.conf
      line: "*Remove = rsyslogd.s (user|group)id changed to"

  - lineinfile:
      dest: /etc/logwatch/conf/services/rsyslogd.conf
      line: "*Remove = : Acquired UNIX socket"

  - lineinfile:
      dest: /etc/logwatch/conf/services/rsyslogd.conf
      line: "*Remove = exiting on signal 15"

  - lineinfile:
      dest: /etc/logwatch/conf/services/postfix.conf
      create: yes
      line: '*Remove = lost connection .* from unknown\[unknown\]'

  - lineinfile:
      dest: /etc/logwatch/conf/services/postfix.conf
      line: '*Remove = synacor.*Blacklisted by Internal Reputation Service'

  - lineinfile:
      dest: /etc/logwatch/conf/services/postfix.conf
      line: '*Remove = netidentity.*blocked using urbl\.hostedemail\.com'

  - lineinfile:
      dest: /etc/logwatch/conf/services/postfix.conf
      line: '*Remove = magellanhealth.*poor reputation'

  - lineinfile:
      dest: /etc/logwatch/conf/services/postfix.conf
      line: '*Remove = improper command pipelining'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      create: yes
      line: "*OnlyService = sshd"
      insertbefore: '\*Remove'
      firstmatch: yes

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Exiting on signal 15'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Server listening on .* port {{item}}'
    with_items: '{{relay_ssh_ports}}'
    when: relay_ssh_ports is defined

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Accepted.*xtK5LjLojcccD9XfFDng6QNPWijHnA8VGyeZxQPwCMo'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: "*Remove = session (opened|closed) for user root"

  # It's safe to ignore these when we only allow public key authentication.
  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Failed password for'
    when: disable_sshd_password_authentication is defined and
      disable_sshd_password_authentication

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = check pass; user unknown'

  # It's safe to ignore these when we only allow public key authentication.
  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = authentication failure'
    when: disable_sshd_password_authentication is defined and
      disable_sshd_password_authentication

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Invalid user'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Did not receive identification string'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Bad protocol version identification'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Connection (reset|closed) by .*preauth'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Received disconnect from'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Disconnected from'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = ignoring max retries'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = maximum authentication attempts exceeded'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Received signal 15; terminating'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Unable to negotiate with'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Change of username or service not allowed'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = Accepted publickey for'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sshd.conf
      line: '*Remove = pam_unix\(sshd:session\): session (opened|closed) for'

  # It's safe to ignore these when we only allow public key authentication.
  - lineinfile:
      dest: /etc/logwatch/conf/services/pam_unix.conf
      create: yes
      line: '*Remove = sshd:auth.*(user unknown|authentication failure)'
    when: disable_sshd_password_authentication is defined and
      disable_sshd_password_authentication

  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*OnlyService = (kernel:( \[[ 0-9\.]+\])?)?\s*(type=[0-9]+\s*)?audit.*'
      create: yes

  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*Remove = res=success'
      
  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*Remove = op=login acct=\"(\(unknown\)|bin|root|ftp|operator)\" .*res=failed'
      
  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*Remove = op=PAM:bad_ident .*acct=\"\?\" .*res=failed'
      
  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*Remove = op=maxtries exceeded'

  - lineinfile:
      dest: /etc/logwatch/conf/services/audit.conf
      line: '*Remove = NETFILTER_CFG table=filter family=[0-9]+ entries=[0-9]+$'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sudo.conf
      line: '*OnlyService = sudo'
      create: yes

  - lineinfile:
      dest: /etc/logwatch/conf/services/sudo.conf
      line: '*RemoveHeaders'

  - lineinfile:
      dest: /etc/logwatch/conf/services/sudo.conf
      line: '*Remove = Cannot create session: Already running in a session'

  - block:
    - lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^Port\s+{{item}}\b'
        line: 'Port {{item}}'
      with_items: '{{relay_ssh_ports}}'
      register: sshd_port
    - seport:
        ports: '{{item}}'
        proto: tcp
        setype: ssh_port_t
        state: present
      with_items: '{{relay_ssh_ports}}'
      when: 'getenforce.stdout is defined and "Enforcing" in getenforce.stdout'
    when: relay_ssh_ports is defined

  - lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin\s+'
      line: 'PermitRootLogin prohibit-password'
    register: sshd_root_login

  - lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication\s+'
      line: 'PasswordAuthentication no'
    when: disable_sshd_password_authentication is defined and
      disable_sshd_password_authentication
    register: sshd_password_authentication
    
  - service: name=sshd state=reloaded
    when: sshd_port.changed or sshd_root_login.changed or
      (sshd_password_authentication is defined and
      sshd_password_authentication.changed)

  - ufw: state=enabled logging=off

  # On Ubuntu, `ufw enable` enables the systemd service, but on Fedora (at
  # least) it does not, so enable it explicitly just to be safe.
  - service: name=ufw enabled=yes

  - ufw: rule=allow port=smtp

  - ufw: rule=allow port={{item}}
    with_items: '{{relay_ssh_ports}}'
    when: relay_ssh_ports is defined

- import_playbook: dnsbl-check/dnsbl-check.yml
